apiVersion: v1
kind: Pod
metadata:
  name: builder
  labels:
    io.containers.autoupdate: registry
spec:
  restartPolicy: Never
  containers:
    - name: aosp
      image: ghcr.io/martinx3-androiddevelopment/scripts_build:android-13
      imagePullPolicy: Always
      command: ["ROM/SODP/XPERIA_TAMA/SonyAOSP/build.sh"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - mountPath: /code
          name: code-volume
        - mountPath: /out
          name: out-volume
        - mountPath: /tmp
          name: tmp-volume
  volumes:
    - name: code-volume
      hostPath:
        path: /home/developer/android/rom/sonyAOSP/13/code
        type: Directory
    - name: out-volume
      hostPath:
        path: /home/developer/android/rom/sonyAOSP/13/out
        type: Directory
    - name: tmp-volume
      emptyDir:
        medium: Memory
        sizeLimit: 512Mi
