name: Publishing image to GitHub Packages
on:
  push:
    branches: [ "android-15" ]
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: ${{ github.repository }}
          containerfiles: |
            ./Containerfile
          oci: true
          tags: |
            ${{ github.ref_name }}
      - name: Push To ghcr.io
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          image: ${{ steps.build_image.outputs.image }}
          password: ${{ github.token }}
          registry: ghcr.io
          tags: ${{ steps.build_image.outputs.tags }}
          username: ${{ github.actor }}
