name: Publishing image to GitHub Packages
on:
  push:
    branches: [ "android-13" ]
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@b4dc19b4ba891854660ab1f88a097d45aa158f76 # v2
        with:
          image: ${{ github.repository }}
          containerfiles: |
            ./Containerfile
          oci: true
          tags: |
            ${{ github.ref_name }}
      - name: Push To ghcr.io
        uses: redhat-actions/push-to-registry@9986a6552bc4571882a4a67e016b17361412b4df # v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          password: ${{ github.token }}
          registry: ghcr.io
          tags: ${{ steps.build_image.outputs.tags }}
          username: ${{ github.actor }}
